voices : 
    en-AU-Annette (AU Female): en-AU-AnnetteNeural
    en-AU-Carly (AU Female): en-AU-CarlyNeural
    en-AU-Darren (AU Male): en-AU-DarrenNeural
    en-AU-Duncan (AU Male): en-AU-DuncanNeural
    en-AU-Elsie (AU Female): en-AU-ElsieNeural
    en-AU-Freya (AU Female): en-AU-FreyaNeural
    en-AU-Joanne (AU Female): en-AU-JoanneNeural
    en-AU-Ken (AU Male): en-AU-KenNeural
    en-AU-Kim (AU Female): en-AU-KimNeural
    en-AU-Natasha (AU Female): en-AU-NatashaNeural
    en-AU-Neil (AU Male): en-AU-NeilNeural
    en-AU-Tim (AU Male): en-AU-TimNeural
    en-AU-Tina (AU Female): en-AU-TinaNeural
    en-AU-William (AU Male): en-AU-WilliamNeural
    en-CA-Clara (CA Female): en-CA-ClaraNeural
    en-CA-Liam (CA Male): en-CA-LiamNeural
    en-GB-Abbi (GB Female): en-GB-AbbiNeural
    en-GB-Alfie (GB Male): en-GB-AlfieNeural
    en-GB-Bella (GB Female): en-GB-BellaNeural
    en-GB-Elliot (GB Male): en-GB-ElliotNeural
    en-GB-Ethan (GB Male): en-GB-EthanNeural
    en-GB-Hollie (GB Female): en-GB-HollieNeural
    en-GB-Libby (GB Female): en-GB-LibbyNeural
    en-GB-Maisie (GB Female): en-GB-MaisieNeural
    en-GB-Mia (GB Female): en-GB-MiaNeural
    en-GB-Noah (GB Male): en-GB-NoahNeural
    en-GB-Oliver (GB Male): en-GB-OliverNeural
    en-GB-Olivia (GB Female): en-GB-OliviaNeural
    en-GB-Ryan (GB Male): en-GB-RyanNeural
    en-GB-Sonia (GB Female): en-GB-SoniaNeural
    en-GB-Thomas (GB Male): en-GB-ThomasNeural
    en-HK-Sam (HK Male): en-HK-SamNeural
    en-HK-Yan (HK Female): en-HK-YanNeural
    en-IE-Connor (IE Male): en-IE-ConnorNeural
    en-IE-Emily (IE Female): en-IE-EmilyNeural
    en-IN-Aarav (IN Male): en-IN-AaravNeural
    en-IN-Aarti (IN Female): en-IN-AartiNeural
    en-IN-Aashi (IN Female): en-IN-AashiNeural
    en-IN-Ananya (IN Female): en-IN-AnanyaNeural
    en-IN-Arjun (IN Male): en-IN-ArjunNeural
    en-IN-Kavya (IN Female): en-IN-KavyaNeural
    en-IN-Kunal (IN Male): en-IN-KunalNeural
    en-IN-Neerja (IN Female): en-IN-NeerjaNeural
    en-IN-Prabhat (IN Male): en-IN-PrabhatNeural
    en-IN-Rehaan (IN Male): en-IN-RehaanNeural
    en-KE-Asilia (KE Female): en-KE-AsiliaNeural
    en-KE-Chilemba (KE Male): en-KE-ChilembaNeural
    en-NG-Abeo (NG Male): en-NG-AbeoNeural
    en-NG-Ezinne (NG Female): en-NG-EzinneNeural
    en-NZ-Mitchell (NZ Male): en-NZ-MitchellNeural
    en-NZ-Molly (NZ Female): en-NZ-MollyNeural
    en-PH-James (PH Male): en-PH-JamesNeural
    en-PH-Rosa (PH Female): en-PH-RosaNeural
    en-SG-Luna (SG Female): en-SG-LunaNeural
    en-SG-Wayne (SG Male): en-SG-WayneNeural
    en-TZ-Elimu (TZ Male): en-TZ-ElimuNeural
    en-TZ-Imani (TZ Female): en-TZ-ImaniNeural
    en-US-Amber (US Female): en-US-AmberNeural
    en-US-Ana (US Female): en-US-AnaNeural
    en-US-Andrew (US Male): en-US-AndrewNeural
    en-US-Aria (US Female): en-US-AriaNeural
    en-US-Ashley (US Female): en-US-AshleyNeural
    en-US-Ava (US Female): en-US-AvaNeural
    en-US-Brandon (US Male): en-US-BrandonNeural
    en-US-Brian (US Male): en-US-BrianNeural
    en-US-Christopher (US Male): en-US-ChristopherNeural
    en-US-Cora (US Female): en-US-CoraNeural
    en-US-Davis (US Male): en-US-DavisNeural
    en-US-Elizabeth (US Female): en-US-ElizabethNeural
    en-US-Emma (US Female): en-US-EmmaNeural
    en-US-Eric (US Male): en-US-EricNeural
    en-US-Guy (US Male): en-US-GuyNeural
    en-US-Jacob (US Male): en-US-JacobNeural
    en-US-Jane (US Female): en-US-JaneNeural
    en-US-Jason (US Male): en-US-JasonNeural
    en-US-Jenny (US Female): en-US-JennyNeural
    en-US-Kai (US Male): en-US-KaiNeural
    en-US-Luna (US Female): en-US-LunaNeural
    en-US-Michelle (US Female): en-US-MichelleNeural
    en-US-Monica (US Female): en-US-MonicaNeural
    en-US-Nancy (US Female): en-US-NancyNeural
    en-US-Roger (US Male): en-US-RogerNeural
    en-US-Sara (US Female): en-US-SaraNeural
    en-US-Steffan (US Male): en-US-SteffanNeural
    en-US-Tony (US Male): en-US-TonyNeural
    en-ZA-Leah (ZA Female): en-ZA-LeahNeural
    en-ZA-Luke (ZA Male): en-ZA-LukeNeural
    ta-IN-Pallavi (IN Female): ta-IN-PallaviNeural
    ta-IN-Valluvar (IN Male): ta-IN-ValluvarNeural
    ta-LK-Kumar (LK Male): ta-LK-KumarNeural
    ta-LK-Saranya (LK Female): ta-LK-SaranyaNeural
    ta-MY-Kani (MY Female): ta-MY-KaniNeural
    ta-MY-Surya (MY Male): ta-MY-SuryaNeural
    ta-SG-Anbu (SG Male): ta-SG-AnbuNeural
    ta-SG-Venba (SG Female): ta-SG-VenbaNeural
    